# Generated by Django 3.2.4 on 2021-08-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('image', models.ImageField(upload_to='product/')),
            ],
        ),
    ]
