# Generated by Django 3.2.4 on 2021-08-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=300)),
                ('mobnumber', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=25)),
                ('zip', models.CharField(max_length=6)),
            ],
        ),
    ]
