# Generated by Django 3.2.4 on 2021-09-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ON PROCESS', 'ON Process'), ('DELIEVERED', 'Delieverd'), ('ORDER PLACED', 'Order Placed'), ('COMPLETED', 'Completed'), ('ON TRANSIT', 'On Transit'), ('CANCELLED', 'Cancelled')], max_length=30),
        ),
    ]
